- id: '9039000000021'
  alias: Living Room Lights On
  action:
  - alias: Living Room Lights On
    service: light.turn_on
    entity_id: group.living_room_lights
  condition: []
  trigger:
  - device_id: bad834da0b8d11ecba358ff12beb7c76
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  mode: single

- id: '9039000000022'
  alias: Living Room Lights Off
  action:
  - alias: Living Room Lights Off
    service: light.turn_off
    entity_id: group.living_room_lights
  condition: []
  trigger:
  - device_id: bad834da0b8d11ecba358ff12beb7c76
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  mode: single

- id: '9039000000023'
  alias: Living Room Lights Brighter
  action:
  - device_id: 1fa91f7800c411eb985f791156e3999c
    domain: light
    entity_id: group.living_room_lights
    type: brightness_increase
  condition: []
  trigger:
  - device_id: bad834da0b8d11ecba358ff12beb7c76
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  mode: single

- id: '9039000000024'
  alias: Living Room Lights Dimmer
  action:
  - device_id: 1fa91f7800c411eb985f791156e3999c
    domain: light
    entity_id: group.living_room_lights
    type: brightness_decrease
  condition: []
  trigger:
  - device_id: bad834da0b8d11ecba358ff12beb7c76
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  mode: single

