
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

remote:           
    - platform: broadlink
      host: !secret broadlink_ip
      mac: !secret broadlink_mac
      type: rm4_mini


# foo
