version: '3.2'
services:
  homeassistant:
    container_name: homeassistant
    #image: "ghcr.io/home-assistant/home-assistant:stable"
    image: "homeassistant/home-assistant:0.115.1"
    #network_mode: host
    ports:
      - "8123:8123/tcp"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./log/homeassistant.log
        target: /config/homeassistant.log
      - type: bind
        source: ./log/home-assistant_v2.db
        target: /config/home-assistant_v2.db
      - type: bind
        source: ./log/home-assistant_v2.db-shm
        target: /config/home-assistant_v2.db-shm
      - type: bind
        source: ./log/home-assistant_v2.db-wal
        target: /config/home-assistant_v2.db-wal
      - ./config:/config
    restart: unless-stopped
    privileged: true
